## Как провести одномерный ABC-анализ

Начинаем с загрузки библиотеки Pandas

In [30]:
import pandas as pd

Устанавливаем сразу формат выгрузки данных из файла.
Первая функция - максимальное количество столбцов 40.
Вторая функция - присваиваем стобцам с цисловыми значени формат плавающей точки с двумя знаками после запятой.

In [31]:
pd.set_option('display.max_columns', 40)
pd.set_option('display.float_format', '{:.2f}'.format)

Настраиваем путь к файлу.
Импортируем библиотеку pathlib
Переменной base_dir присваиваем путь к папке где лежит файл (директория).
Переменной file_path указываем файл, который стоит использовать с учетом ранее сформированной переменной base_dir

In [32]:
from pathlib import Path
# Папка, где находится текущий скрипт/ноутбук
base_dir = Path('C:/Users/MACHENIKE/VadimLearn/Vadim-Learn/data').parent  # для .py файлов
# или если вы в Jupyter:
# base_dir = Path.cwd()
file_path = base_dir / 'data' / 'data.csv'

Переменной df - определяем чтение содержимого файла data.csv

In [33]:
df = pd.read_csv(file_path, encoding='1251')

Вызваем переменную для просмотра двух верхних позиций. Обращаю внимание, что фунциями выше мы задали формат числовых значений столбцов.

In [34]:
df.head(2)

,DR_Dat,DR_Tim,DR_NChk,DR_NDoc,DR_Apt,DR_Kkm,DR_TDoc,DR_TPay,DR_CDrugs,DR_NDrugs,DR_Suppl,DR_Prod,DR_Kol,DR_CZak,DR_CRoz,DR_SDisc,DR_CDisc,DR_BCDisc,DR_TabEmpl,DR_VZak,DR_Pos
0,2022-08-11,10:15:35,2173,2004598,2,22577,Розничная реализация,18,45399,ЦИПРОЛЕТ 3МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП. /Д-...,Катрен г.Химки,Д-р Редди с Лабораторис Лтд / Dr.REDDY's,1.00,41.08,51.00,12.00,925.00,200000000492.00,205,1,1.00
1,2022-08-11,10:27:46,2174,2004598,2,22577,Розничная реализация,15,261519,ПЕРЕКИСЬ ВОДОРОДА 3% 100МЛ. №40 Р-Р ФЛ.,Катрен г.Химки,ФЛОРА КАВКАЗА ОАО,1.00,18.61,31.00,3.00,9.00,200010010204.00,205,1,1.00

Проверим форматы данных нашей таблицы.

In [35]:
df.dtypes

DR_Dat            str
DR_Tim            str
DR_NChk         int64
DR_NDoc         int64
DR_Apt          int64
DR_Kkm          int64
DR_TDoc           str
DR_TPay         int64
DR_CDrugs       int64
DR_NDrugs         str
DR_Suppl          str
DR_Prod           str
DR_Kol        float64
DR_CZak       float64
DR_CRoz       float64
DR_SDisc      float64
DR_CDisc      float64
DR_BCDisc     float64
DR_TabEmpl      int64
DR_VZak         int64
DR_Pos        float64
dtype: object

Задаем переменную groupped_df, ей определям группировку по колонке DR_NDr и делаем агрегирование (сумма) по колонке DR_Ko - количество.

In [36]:
groupped_df = df.groupby('DR_NDrugs').agg({'DR_Kol': sum})
groupped_df

                                                    DR_Kol
DR_NDrugs
7 СЕМЬ ДНЕЙ МАСКА Д/ЛИЦА СУББОТА РОМАНТ. ПЕРЕД ...    1.00
9 МЕСЯЦЕВ ФОЛИЕВАЯ К-ТА 0,4МГ. №30 ТАБ. П/П/О /...    1.00
911-ГЕЛЬ-БАЛЬЗАМ Д/СУСТАВОВ ОКОПНИК 100МЛ. ТУБА       2.00
911-ГЕЛЬ-БАЛЬЗАМ Д/СУСТАВОВ САБЕЛЬНИК 100МЛ.          2.00
911-ГЕЛЬ-БАЛЬЗАМ Д/ТЕЛА БИШОФИТ П/БОЛИ В СУСТАВ...    1.00
...                                                    ...
Я САМАЯ ВАТНЫЕ ПАЛОЧКИ №100 СТАКАН                    1.00
ЯНТАРНАЯ К-ТА 100МГ. №10 ТАБ. (БАД) /МАРБИОФАРМ/      2.00
ЯНТАРНАЯ К-ТА ПРЕМИУМ 100МГ. №20 ТАБ. (БАД) /БА...    1.00
ЯНТАРНАЯ К-ТА ФОРП 100МГ. №10 ТАБ.                    3.00
ЯРИНА №21 ТАБ. П/П/О                                  1.00

[1876 rows x 1 columns]

Сделал допонитеную обработку, чтобы посмотреть отсортированное по количесту таблицу.

In [37]:
groupped_df = df.groupby('DR_NDrugs').agg({'DR_Kol': sum}).sort_values(by='DR_Kol', ascending=False)
groupped_df

                                                    DR_Kol
DR_NDrugs
ПАКЕТ                                               126.00
ЦЕФТРИАКСОН 1Г. №1 ПОР. Д/Р-РА Д/В/В,В/М ФЛ. /Л...   60.00
НАФТИЗИН 0,1% 15МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. /ЛЕККО/     48.00
ЛЕЙКОПЛАСТЫРЬ БАКТЕР. 2,5Х7,2 №1 /ВЕРОФАРМ/          40.00
СНУП 0,1% 90МКГ/ДОЗА 15МЛ. НАЗАЛ.СПРЕЙ ФЛ. /ШТАДА/   35.00
...                                                    ...
НАТРИЯ ХЛОРИД 0,9% 400МЛ. №16 Р-Р Д/ИНФ. КОНТ. ...    0.06
СФМ ШПРИЦ 2МЛ. 3-Х КОМП. 0,63Х32ММ 23G №100 [SFM]     0.05
СФМ ШПРИЦ 50МЛ. 3-Х КОМП. 1,2X40ММ 18G №25 [SFM]      0.04
ДЕРМАГРИП ХАЙ РИСК ПЕРЧАТКИ ЛАТ. СМОТР. Н/СТЕР....    0.04
СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. ТЕКСТУРИР. Н/О...    0.02

[1876 rows x 1 columns]

Перезаписываем переменную groupped_df только теперь рассчитываем долю каждой позиции (лекарства) для расчета используем количетво, которое получилось в предыдущем вычислении и сумму всего количества, которую рассчитываем самостоятельно. Далее используем функцию sort_values(ascending=False), чтобы отсортировать по убыванию. Обрати внимание, если вместо False использовать True, то сортировка будет осуществлена по возрастанию.

In [38]:
groupped_df = (groupped_df['DR_Kol'] / sum(groupped_df['DR_Kol'])).sort_values(ascending=False)
groupped_df

DR_NDrugs
ПАКЕТ                                                                         0.03
ЦЕФТРИАКСОН 1Г. №1 ПОР. Д/Р-РА Д/В/В,В/М ФЛ. /ЛЕККО/                          0.01
НАФТИЗИН 0,1% 15МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. /ЛЕККО/                              0.01
ЛЕЙКОПЛАСТЫРЬ БАКТЕР. 2,5Х7,2 №1 /ВЕРОФАРМ/                                   0.01
СНУП 0,1% 90МКГ/ДОЗА 15МЛ. НАЗАЛ.СПРЕЙ ФЛ. /ШТАДА/                            0.01
                                                                              ...
НАТРИЯ ХЛОРИД 0,9% 400МЛ. №16 Р-Р Д/ИНФ. КОНТ. /МОСФАРМ/                      0.00
СФМ ШПРИЦ 2МЛ. 3-Х КОМП. 0,63Х32ММ 23G №100 [SFM]                             0.00
СФМ ШПРИЦ 50МЛ. 3-Х КОМП. 1,2X40ММ 18G №25 [SFM]                              0.00
ДЕРМАГРИП ХАЙ РИСК ПЕРЧАТКИ ЛАТ. СМОТР. Н/СТЕР. Н/ОПУДР Р.L №50 (25ПАР)       0.00
СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. ТЕКСТУРИР. Н/ОПУДР. Р.L №100 (50ПАР) [SFM]   0.00
Name: DR_Kol, Length: 1876, dtype: float64

Теперь используем функцияю cumsum() чтобы рассчитать накопительным итогом количество и сбросить индексы.

In [39]:
groupped_df = groupped_df.cumsum().reset_index()
groupped_df

                                              DR_NDrugs  DR_Kol
0                                                 ПАКЕТ    0.03
1     ЦЕФТРИАКСОН 1Г. №1 ПОР. Д/Р-РА Д/В/В,В/М ФЛ. /...    0.04
2      НАФТИЗИН 0,1% 15МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. /ЛЕККО/    0.05
3           ЛЕЙКОПЛАСТЫРЬ БАКТЕР. 2,5Х7,2 №1 /ВЕРОФАРМ/    0.06
4     СНУП 0,1% 90МКГ/ДОЗА 15МЛ. НАЗАЛ.СПРЕЙ ФЛ. /ШТ...    0.07
...                                                 ...     ...
1871  НАТРИЯ ХЛОРИД 0,9% 400МЛ. №16 Р-Р Д/ИНФ. КОНТ....    1.00
1872  СФМ ШПРИЦ 2МЛ. 3-Х КОМП. 0,63Х32ММ 23G №100 [SFM]    1.00
1873   СФМ ШПРИЦ 50МЛ. 3-Х КОМП. 1,2X40ММ 18G №25 [SFM]    1.00
1874  ДЕРМАГРИП ХАЙ РИСК ПЕРЧАТКИ ЛАТ. СМОТР. Н/СТЕР...    1.00
1875  СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. ТЕКСТУРИР. Н/...    1.00

[1876 rows x 2 columns]

Для дальнейшей работы нам понадобится библиотека numpy - загружаем ее.

In [40]:
import numpy as np

Фомриуем новый стоблец дата фрейма groupped_df - ['abc'], для этого используем функцию сравнения из numpy -  np.where (), где определяем каждому продукту - продуктовую группу, если значение индеска до 0,8 - (80%), то это группа A, если меньше 0,95 - (95%), то это группа B, остальное группа C.

In [41]:
groupped_df['abc'] = np.where(groupped_df['DR_Kol'] < 0.8, 'A', np.where(groupped_df['DR_Kol'] < 0.95, 'B', 'C'))
groupped_df

                                              DR_NDrugs  DR_Kol abc
0                                                 ПАКЕТ    0.03   A
1     ЦЕФТРИАКСОН 1Г. №1 ПОР. Д/Р-РА Д/В/В,В/М ФЛ. /...    0.04   A
2      НАФТИЗИН 0,1% 15МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. /ЛЕККО/    0.05   A
3           ЛЕЙКОПЛАСТЫРЬ БАКТЕР. 2,5Х7,2 №1 /ВЕРОФАРМ/    0.06   A
4     СНУП 0,1% 90МКГ/ДОЗА 15МЛ. НАЗАЛ.СПРЕЙ ФЛ. /ШТ...    0.07   A
...                                                 ...     ...  ..
1871  НАТРИЯ ХЛОРИД 0,9% 400МЛ. №16 Р-Р Д/ИНФ. КОНТ....    1.00   C
1872  СФМ ШПРИЦ 2МЛ. 3-Х КОМП. 0,63Х32ММ 23G №100 [SFM]    1.00   C
1873   СФМ ШПРИЦ 50МЛ. 3-Х КОМП. 1,2X40ММ 18G №25 [SFM]    1.00   C
1874  ДЕРМАГРИП ХАЙ РИСК ПЕРЧАТКИ ЛАТ. СМОТР. Н/СТЕР...    1.00   C
1875  СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. ТЕКСТУРИР. Н/...    1.00   C

[1876 rows x 3 columns]

Вызовем таблицу с элементами, которые попадают в групп 'B'.

In [42]:
groupped_df[groupped_df['abc'] == 'B']

                                              DR_NDrugs  DR_Kol abc
938   МАГНИЙ ДИАСПОРАЛ 300 5Г. №20 ГРАН. Д/Р-РА Д/ПР...    0.80   B
939                 МАГНИЙ В6 1250МГ. №60 ТАБ. /ЭВАЛАР/    0.80   B
940                            МАГНЕРОТ 500МГ. №50 ТАБ.    0.80   B
941                            МАГНЕРОТ 500МГ. №20 ТАБ.    0.80   B
942                            МАГНЕЛИС В6 №90 ТАБ. П/О    0.80   B
...                                                 ...     ...  ..
1621           УМИФЕНОВИР 100МГ. №20 КАПС. /АТОЛЛ/ОЗОН/    0.95   B
1622                        УГОЛЬ БЕЛЫЙ 700МГ. №10 ТАБ.    0.95   B
1623  УГОЛЬ АКТИВИРОВАННЫЙ 250МГ. №20 ТАБ. /ФАРМСТАН...    0.95   B
1624   УАН ТАЧ ТЕСТ-ПОЛОСКИ СЕЛЕКТ ПЛЮС №25 [ONE TOUCH]    0.95   B
1625  УАН ТАЧ ТЕСТ-ПОЛОСКИ СЕЛЕКТ ПЛЮС №100 [ONE TOUCH]    0.95   B

[688 rows x 3 columns]

## Как провести многомерный ABC-анализ

Теперь проходим похожий путь, только теперь вместе с количеством мы будем использовать розничную цену.
Переменной groupped_df группируем наш дата фрейм по столбцу лекарства, и суммируем колонки количества и розничной цены продажи.

In [47]:
groupped_df = df.groupby('DR_NDrugs').agg({'DR_Kol': sum, 'DR_CRoz': sum})
groupped_df

                                                    DR_Kol  DR_CRoz
DR_NDrugs
7 СЕМЬ ДНЕЙ МАСКА Д/ЛИЦА СУББОТА РОМАНТ. ПЕРЕД ...    1.00    93.00
9 МЕСЯЦЕВ ФОЛИЕВАЯ К-ТА 0,4МГ. №30 ТАБ. П/П/О /...    1.00   144.00
911-ГЕЛЬ-БАЛЬЗАМ Д/СУСТАВОВ ОКОПНИК 100МЛ. ТУБА       2.00   216.00
911-ГЕЛЬ-БАЛЬЗАМ Д/СУСТАВОВ САБЕЛЬНИК 100МЛ.          2.00   208.00
911-ГЕЛЬ-БАЛЬЗАМ Д/ТЕЛА БИШОФИТ П/БОЛИ В СУСТАВ...    1.00   100.00
...                                                    ...      ...
Я САМАЯ ВАТНЫЕ ПАЛОЧКИ №100 СТАКАН                    1.00    65.00
ЯНТАРНАЯ К-ТА 100МГ. №10 ТАБ. (БАД) /МАРБИОФАРМ/      2.00    27.00
ЯНТАРНАЯ К-ТА ПРЕМИУМ 100МГ. №20 ТАБ. (БАД) /БА...    1.00    52.00
ЯНТАРНАЯ К-ТА ФОРП 100МГ. №10 ТАБ.                    3.00    28.00
ЯРИНА №21 ТАБ. П/П/О                                  1.00  1292.00

[1876 rows x 2 columns]

Повторям, то что делали на предыдущем уроке.
Формируем дополнительный столбец в Дата Фрейме groupped_df - 'rel_kol' в котором рассчитываем долю от общей суммы по столбцу DR_Kol.

In [48]:
groupped_df['rel_kol'] = groupped_df['DR_Kol'] / sum(groupped_df['DR_Kol'])
groupped_df

                                                    DR_Kol  DR_CRoz  rel_kol
DR_NDrugs
7 СЕМЬ ДНЕЙ МАСКА Д/ЛИЦА СУББОТА РОМАНТ. ПЕРЕД ...    1.00    93.00     0.00
9 МЕСЯЦЕВ ФОЛИЕВАЯ К-ТА 0,4МГ. №30 ТАБ. П/П/О /...    1.00   144.00     0.00
911-ГЕЛЬ-БАЛЬЗАМ Д/СУСТАВОВ ОКОПНИК 100МЛ. ТУБА       2.00   216.00     0.00
911-ГЕЛЬ-БАЛЬЗАМ Д/СУСТАВОВ САБЕЛЬНИК 100МЛ.          2.00   208.00     0.00
911-ГЕЛЬ-БАЛЬЗАМ Д/ТЕЛА БИШОФИТ П/БОЛИ В СУСТАВ...    1.00   100.00     0.00
...                                                    ...      ...      ...
Я САМАЯ ВАТНЫЕ ПАЛОЧКИ №100 СТАКАН                    1.00    65.00     0.00
ЯНТАРНАЯ К-ТА 100МГ. №10 ТАБ. (БАД) /МАРБИОФАРМ/      2.00    27.00     0.00
ЯНТАРНАЯ К-ТА ПРЕМИУМ 100МГ. №20 ТАБ. (БАД) /БА...    1.00    52.00     0.00
ЯНТАРНАЯ К-ТА ФОРП 100МГ. №10 ТАБ.                    3.00    28.00     0.00
ЯРИНА №21 ТАБ. П/П/О                                  1.00  1292.00     0.00

[1876 rows x 3 columns]

Проводим сортировку дата фрейма groupped_df по возрастанию по колонке 'rel_kol' и перезаписываем его.

In [49]:
groupped_df = groupped_df.sort_values('rel_kol', ascending=False)
groupped_df

                                                    DR_Kol  DR_CRoz  rel_kol
DR_NDrugs
ПАКЕТ                                               126.00   248.00     0.03
ЦЕФТРИАКСОН 1Г. №1 ПОР. Д/Р-РА Д/В/В,В/М ФЛ. /Л...   60.00  2280.00     0.01
НАФТИЗИН 0,1% 15МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. /ЛЕККО/     48.00   552.00     0.01
ЛЕЙКОПЛАСТЫРЬ БАКТЕР. 2,5Х7,2 №1 /ВЕРОФАРМ/          40.00    28.00     0.01
СНУП 0,1% 90МКГ/ДОЗА 15МЛ. НАЗАЛ.СПРЕЙ ФЛ. /ШТАДА/   35.00  4215.00     0.01
...                                                    ...      ...      ...
НАТРИЯ ХЛОРИД 0,9% 400МЛ. №16 Р-Р Д/ИНФ. КОНТ. ...    0.06   669.00     0.00
СФМ ШПРИЦ 2МЛ. 3-Х КОМП. 0,63Х32ММ 23G №100 [SFM]     0.05   918.00     0.00
СФМ ШПРИЦ 50МЛ. 3-Х КОМП. 1,2X40ММ 18G №25 [SFM]      0.04  1324.00     0.00
ДЕРМАГРИП ХАЙ РИСК ПЕРЧАТКИ ЛАТ. СМОТР. Н/СТЕР....    0.04  2000.00     0.00
СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. ТЕКСТУРИР. Н/О...    0.02   988.00     0.00

[1876 rows x 3 columns]

Формируем дополнительный столбец в дата фрейме groupped_df - cumsum_kol, который рассчитывается куммулитивным итогом от rel_sum.

In [50]:
groupped_df['cumsum_kol'] = groupped_df['rel_kol'].cumsum()
groupped_df

,DR_Kol,DR_CRoz,rel_kol,cumsum_kol
DR_NDrugs,,,,
ПАКЕТ,126.00,248.00,0.03,0.03
"ЦЕФТРИАКСОН 1Г. №1 ПОР. Д/Р-РА Д/В/В,В/М ФЛ. /ЛЕККО/",60.00,2280.00,0.01,0.04
"НАФТИЗИН 0,1% 15МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. /ЛЕККО/",48.00,552.00,0.01,0.05
"ЛЕЙКОПЛАСТЫРЬ БАКТЕР. 2,5Х7,2 №1 /ВЕРОФАРМ/",40.00,28.00,0.01,0.06
"СНУП 0,1% 90МКГ/ДОЗА 15МЛ. НАЗАЛ.СПРЕЙ ФЛ. /ШТАДА/",35.00,4215.00,0.01,0.07
...,...,...,...,...
"НАТРИЯ ХЛОРИД 0,9% 400МЛ. №16 Р-Р Д/ИНФ. КОНТ. /МОСФАРМ/",0.06,669.00,0.00,1.00
"СФМ ШПРИЦ 2МЛ. 3-Х КОМП. 0,63Х32ММ 23G №100 [SFM]",0.05,918.00,0.00,1.00
"СФМ ШПРИЦ 50МЛ. 3-Х КОМП. 1,2X40ММ 18G №25 [SFM]",0.04,1324.00,0.00,1.00
ДЕРМАГРИП ХАЙ РИСК ПЕРЧАТКИ ЛАТ. СМОТР. Н/СТЕР. Н/ОПУДР Р.L №50 (25ПАР),0.04,2000.00,0.00,1.00
СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. ТЕКСТУРИР. Н/ОПУДР. Р.L №100 (50ПАР) [SFM],0.02,988.00,0.00,1.00

Формируем дополнительный стоблец в наш дата фрейма groupped_df - abc_kol, в котором записываем по каждому элементу группу в зависимости от значений кумулятивной суммы элемента.

In [51]:
groupped_df['abc_kol'] = np.where(groupped_df['cumsum_kol'] < 0.8, 'A', np.where(groupped_df['cumsum_kol'] < 0.95, 'B', 'C'))

Выводим полученный дата фрейм для просмотра.

In [52]:
groupped_df

,DR_Kol,DR_CRoz,rel_kol,cumsum_kol,abc_kol
DR_NDrugs,,,,,
ПАКЕТ,126.00,248.00,0.03,0.03,A
"ЦЕФТРИАКСОН 1Г. №1 ПОР. Д/Р-РА Д/В/В,В/М ФЛ. /ЛЕККО/",60.00,2280.00,0.01,0.04,A
"НАФТИЗИН 0,1% 15МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. /ЛЕККО/",48.00,552.00,0.01,0.05,A
"ЛЕЙКОПЛАСТЫРЬ БАКТЕР. 2,5Х7,2 №1 /ВЕРОФАРМ/",40.00,28.00,0.01,0.06,A
"СНУП 0,1% 90МКГ/ДОЗА 15МЛ. НАЗАЛ.СПРЕЙ ФЛ. /ШТАДА/",35.00,4215.00,0.01,0.07,A
...,...,...,...,...,...
"НАТРИЯ ХЛОРИД 0,9% 400МЛ. №16 Р-Р Д/ИНФ. КОНТ. /МОСФАРМ/",0.06,669.00,0.00,1.00,C
"СФМ ШПРИЦ 2МЛ. 3-Х КОМП. 0,63Х32ММ 23G №100 [SFM]",0.05,918.00,0.00,1.00,C
"СФМ ШПРИЦ 50МЛ. 3-Х КОМП. 1,2X40ММ 18G №25 [SFM]",0.04,1324.00,0.00,1.00,C
ДЕРМАГРИП ХАЙ РИСК ПЕРЧАТКИ ЛАТ. СМОТР. Н/СТЕР. Н/ОПУДР Р.L №50 (25ПАР),0.04,2000.00,0.00,1.00,C
СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. ТЕКСТУРИР. Н/ОПУДР. Р.L №100 (50ПАР) [SFM],0.02,988.00,0.00,1.00,C

Теперь выполняем тоже самое для столбца с розницной ценой.
1. Формируем дополнительный столбец rel_roz, как отношение розничной цены элемента к общей сумме розничной цены всех элементов.
2. Сортируем по убыванию столбец rel_roz.
3. Формируем дополнительный столбец cumsum, как куммулятивную сумму столбца rel_roz.
4. Формируем дополнительный столбец abc_roz, в котором каждому элементу присваиваем значение из группы ABC, но основании отбора по столбцу cumsum_roz.

In [53]:
groupped_df['rel_roz'] = groupped_df['DR_CRoz'] / sum(groupped_df['DR_CRoz'])
groupped_df = groupped_df.sort_values('rel_roz', ascending=False)
groupped_df['cumsum_roz'] = groupped_df['rel_roz'].cumsum()
groupped_df['abc_roz'] = np.where(groupped_df['cumsum_roz'] < 0.8, 'A', np.where(groupped_df['cumsum_roz'] < 0.95, 'B', 'C'))

Вывозим избранные столбцы, при этом сбрасываем индекс и делаем соритировку по убыванию по столбцу DR_Croz

In [55]:
groupped_df[['DR_CRoz', 'DR_Kol', 'abc_kol', 'abc_roz']].reset_index().sort_values('DR_CRoz', ascending=False)

,DR_NDrugs,DR_CRoz,DR_Kol,abc_kol,abc_roz
0,"ТЕРАФЛЮ ЛИМОН ОТ ГРИППА И ПРОСТУДЫ 22,1Г. №14 ...",15638.00,7.00,A,A
1,НИМЕСИЛ 100МГ. 2Г. №30 ГРАН. Д/СУСП. Д/ПРИЕМА ...,14445.00,2.80,A,A
2,ИНГАВИРИН 90МГ. №10 КАПС. /ВАЛЕНТА/,13750.00,18.00,A,A
3,ХАРТМАНН БРАНОЛИНД H ПОВЯЗКА СТЕР. 10Х20СМ. №3...,12908.00,0.17,C,A
4,"ЭЛИКВИС 2,5МГ. №60 ТАБ. П/П/О /ПФАЙЗЕР/БРИСТОЛ...",12731.00,5.00,A,A
...,...,...,...,...,...
1871,АСКОРБИНОВАЯ К-ТА 25МГ. АПЕЛЬСИН №10 ТАБ. КРУТ...,10.00,1.00,C,C
1872,КОНТЕЙНЕР Д/СБОРА БИОМАТЕРИАЛА 60МЛ. +ШПАТЕЛЬ ...,10.00,1.00,A,C
1873,АСКОРБИНОВАЯ К-ТА 25МГ. №10 ТАБ. КРУТКА САХ. /...,9.00,7.00,A,C
1874,КЛИНСА БАХИЛЫ СТАНДАРТ №2 (1ПАРА),7.00,2.00,A,C
1875,"Карта LOYALITY 0,01Р",0.34,34.00,A,C

## Как автоматизировать ABC-анализ

Формируем новый дата фрейм из исходной таблицы, который примет на себя элементы, по которым будет производится ABC анализ.
Здесь мы выбираем столбцы DR_NDrugs, DR_Kol, DR_CRoz

In [73]:
df1 = df[['DR_NDrugs', 'DR_Kol', 'DR_CRoz']]
df1.columns

Index(['DR_NDrugs', 'DR_Kol', 'DR_CRoz'], dtype='str')

Вызываем к просмотру новый дата фрейм

In [74]:
df1

                                              DR_NDrugs  DR_Kol  DR_CRoz
0                               ГАСТАЛ №12 ТАБ. Д/РАСС.    1.00   270.00
1      ТОБРОПТ 0,3% 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП. /РОМФАРМ/    1.00   127.00
2     ЭЛИКВИС 5МГ. №60 ТАБ. П/П/О /ПФАЙЗЕР/БРИСТОЛ-М...    1.00  2563.00
3     АРБИДОЛ МАКСИМУМ 200МГ. №10 КАПС. /ОТИСИФАРМ/Ф...    1.00   541.00
4                      ЭНАМ 2,5МГ. №20 ТАБ. /Д-Р РЕДДИ/    1.00    22.00
...                                                 ...     ...      ...
1443   ПАНКРЕАТИН 25ЕД №60 ТАБ.КШ/РАСТВ. П/О /АВЕКСИМА/    1.00    76.00
1444  ДИКЛОФЕНАК 25МГ/МЛ. 3МЛ. №5 Р-Р Д/В/М ВВЕД. АМ...    1.00    51.00
1445                  СИРДАЛУД 4МГ. №30 ТАБ. /НОВАРТИС/    1.00   322.00
1446  МЕРИДИАН МОЧЕПРИЕМНИК ДЕТСКИЙ PD2200 200МЛ. [M...    4.00    12.00
1447  ГЕМАТОГЕН РУССКИЙ КЕДРОВЫЙ ОРЕХ 40Г. ПЛИТКА /Ф...    1.00    30.00

[1448 rows x 3 columns]

В качестве примера, который будем испозовать в дальнейшем создаем новую переменную а, которая формируемт из столбоцов нашего ногового дата фрейма список. а затем исключает из этого списка столбец DR_Kol. Итоге получаем список из наших столбцов без удаленного столбца.

In [75]:
a = list(df1.columns)
a.remove('DR_Kol')
a

['DR_NDrugs', 'DR_CRoz']

В качестве примера формируем словарь, каждый столбец в списке a, будет объявлен ключем, а значение будет определено как сумма.

In [76]:
{col: sum for col in a}

{'DR_NDrugs': <function sum(iterable, /, start=0)>,
 'DR_CRoz': <function sum(iterable, /, start=0)>}

В качестве примера показываем, что при сложении списка с другим списком будет получен новый список

In [77]:
a + [1, 23]

['DR_NDrugs', 'DR_CRoz', 1, 23]

В качестве примера записываем что каждому столбцу col в списке a, может быть использован в качестве суффикса для образования нового столбца.
У в списке a были столбцы DR_NDrugs, DR_CRoz. Используя эти названия и f' мы получили название для нового списка rel_DR_NDrugs, rel_DR_CRoz.

In [78]:
for col in a:
    print(f'rel_{col}')

rel_DR_NDrugs
rel_DR_CRoz

Переменной perform_abc задаем значение дата фрема (наш новый дата фрейм с выбранным наимнованием лекарства, количества и розничной ценой (DR_NDrugs, DR_Kol, DR_CRoz)), в качестве индекса используем R_NDrugs. По нему будет произведен расчет.

In [79]:
perform_abc(df1, index='DR_NDrugs')

,DR_Kol,DR_CRoz,abc_DR_Kol,abc_DR_CRoz
DR_NDrugs,,,,
ДЕТРАЛЕКС 1000МГ. №60 ТАБ. П/П/О,4.00,11948.00,A,A
КСАРЕЛТО 10МГ. №98 ТАБ. П/П/О /БАЙЕР/,0.14,10775.70,C,A
ПРАДАКСА 110МГ. №180 КАПС. /БЕРИНГЕР/,0.33,10375.00,C,A
ЭЛИКВИС 5МГ. №60 ТАБ. П/П/О /ПФАЙЗЕР/БРИСТОЛ-МАЙЕРС/,2.00,5126.00,A,A
ГЕЛАДРИНК ФОРТЕ ПОР. Д/ПРИЕМА ВНУТРЬ АПЕЛЬСИН 420Г. БАНКА,1.00,4985.00,A,A
...,...,...,...,...
БРИЛЛИАНТОВЫЙ ЗЕЛЕН 1% 10МЛ. №1 СПИРТ. Р-Р Д/НАРУЖ.ПРИМ. ФЛ. /САМАРАМЕДПРОМ/,1.00,16.00,B,C
"ХЛОРГЕКСИДИН 0,05% 100МЛ. №1 Р-Р Д/МЕСТ. И НАРУЖ.ПРИМ. ФЛ. ПЭТ. /ТУЛЬСКАЯ ФФ/",1.00,14.00,C,C
МЕРИДИАН МОЧЕПРИЕМНИК ДЕТСКИЙ PD2200 200МЛ. [MERIDIAN],4.00,12.00,A,C
БАХИЛЫ №10 (5ПАР),1.00,10.00,B,C
"Карта LOYALITY 0,01Р",12.00,0.12,A,C

Теперь записываем функцию, которая позволяет автоматически рассчитывать параметры для определения групп ABC по выбранным столбцам.

In [80]:
def perform_abc(df, index):
    """
    На вход подается датафрейм пандас...
    """
    cols = list(df.columns) # формируем переменную cols, как список столбцов нашего дата фрейма.
    cols.remove(index) # перезаписываем нашу переменную cols, удаляя оттуда значение, которое используется в качестве индекса, и по которому расчеты выполнять не будут
    groupped_df = df.groupby(index).agg({col: sum for col in cols}) # формируем новый дата фрейм и производим группировку по индексируемому столбцу, при этом создаем словарь, в котором ключом выступает название столца, а значением выступает сумма
    for col in cols: # теперь формуем цикл для расчета каждого столбца в списке всех столбцов
        groupped_df[f'rel_{col}'] = groupped_df[col] / sum(groupped_df[col]) # формируем новый столбец, в который записываем долю каждого элемента
        groupped_df = groupped_df.sort_values(f'rel_{col}', ascending=False) # перезаписываем дата фрей проведя сортировку по доле каждого элемента
        groupped_df[f'cumsum_{col}'] = groupped_df[f'rel_{col}'].cumsum() # формируем новый столбец, в котором записываем кумулятивную долю элементов
        groupped_df[f'abc_{col}'] = np.where(groupped_df[f'cumsum_{col}'] < 0.8, 'A', np.where(groupped_df[f'cumsum_{col}'] < 0.95, 'B', 'C')) # формируем столбец, в котором записываем долю в зависимости от кумулятивной суммы
    return groupped_df[cols + [f'abc_{col}' for col in cols]] # возвращаем список со столбцами, которые изначально были в дата фрейме и добавлям новые столбцы, которые содержат префикс 'abc'

Задаем значени переменной perform_abc. Получаем новый дата фрейм с указанием групп ABC.

In [81]:
perform_abc(df1, index='DR_NDrugs')

,DR_Kol,DR_CRoz,abc_DR_Kol,abc_DR_CRoz
DR_NDrugs,,,,
ДЕТРАЛЕКС 1000МГ. №60 ТАБ. П/П/О,4.00,11948.00,A,A
КСАРЕЛТО 10МГ. №98 ТАБ. П/П/О /БАЙЕР/,0.14,10775.70,C,A
ПРАДАКСА 110МГ. №180 КАПС. /БЕРИНГЕР/,0.33,10375.00,C,A
ЭЛИКВИС 5МГ. №60 ТАБ. П/П/О /ПФАЙЗЕР/БРИСТОЛ-МАЙЕРС/,2.00,5126.00,A,A
ГЕЛАДРИНК ФОРТЕ ПОР. Д/ПРИЕМА ВНУТРЬ АПЕЛЬСИН 420Г. БАНКА,1.00,4985.00,A,A
...,...,...,...,...
БРИЛЛИАНТОВЫЙ ЗЕЛЕН 1% 10МЛ. №1 СПИРТ. Р-Р Д/НАРУЖ.ПРИМ. ФЛ. /САМАРАМЕДПРОМ/,1.00,16.00,B,C
"ХЛОРГЕКСИДИН 0,05% 100МЛ. №1 Р-Р Д/МЕСТ. И НАРУЖ.ПРИМ. ФЛ. ПЭТ. /ТУЛЬСКАЯ ФФ/",1.00,14.00,C,C
МЕРИДИАН МОЧЕПРИЕМНИК ДЕТСКИЙ PD2200 200МЛ. [MERIDIAN],4.00,12.00,A,C
БАХИЛЫ №10 (5ПАР),1.00,10.00,B,C
"Карта LOYALITY 0,01Р",12.00,0.12,A,C

**Динамика продаж**

## Как оценить динамику продаж

Традиционна начинаем с прописывания пути к файлу

In [71]:
from pathlib import Path
# Папка, где находится текущий скрипт/ноутбук
base_dir = Path('C:/Users/MACHENIKE/VadimLearn/Vadim-Learn/data').parent  # для .py файлов
# или если вы в Jupyter:
# base_dir = Path.cwd()
file_path = base_dir / 'data' / 'data1.csv'

Задаем наш дата фрейм - прочитав файл csv с кодировкой 1251

In [72]:
df = pd.read_csv(file_path, encoding='1251')

Выводим первые пять значений нашего дата фрейма

In [190]:
df.head()

,DR_Dat,DR_Tim,DR_NChk,DR_NDoc,DR_Apt,DR_Kkm,DR_TDoc,DR_TPay,DR_CDrugs,DR_NDrugs,DR_Suppl,DR_Prod,DR_Kol,DR_CZak,DR_CRoz,DR_SDisc,DR_CDisc,DR_BCDisc,DR_TabEmpl,DR_VZak,DR_Pos
0,2022-08-01,08:06:18,1272,13002561,13,22589,Розничная реализация,18,144734,ГАСТАЛ №12 ТАБ. Д/РАСС.,Пульс,TEVA Pharvaceutical Industries Ltd,1.00,196.71,270.00,0.00,NaN,NaN,29,1,1.00
1,2022-08-01,08:38:53,1273,13002561,13,22589,Розничная реализация,15,69661,"ТОБРОПТ 0,3% 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП. /РОМФАРМ/",Пульс,РОМФАРМ КОМПАНИ ( ROMPHARM ),1.00,106.21,127.00,6.00,9.00,200010004357.00,29,1,1.00
2,2022-08-01,08:55:38,1274,13002561,13,22589,Розничная реализация,18,190635,ЭЛИКВИС 5МГ. №60 ТАБ. П/П/О /ПФАЙЗЕР/БРИСТОЛ-М...,ГРАНД КАПИТАЛ СМОЛЕНСК ООО ФК,Пфайзер,1.00,2320.99,2563.00,76.00,9.00,200010018491.00,29,1,1.00
3,2022-08-01,09:00:40,1275,13002561,13,22589,Розничная реализация,18,276370,АРБИДОЛ МАКСИМУМ 200МГ. №10 КАПС. /ОТИСИФАРМ/Ф...,Пульс,ОТИСИФАРМ ПАО,1.00,445.39,541.00,0.00,NaN,NaN,29,1,1.00
4,2022-08-01,09:04:05,1276,13002561,13,22589,Розничная реализация,15,2303,"ЭНАМ 2,5МГ. №20 ТАБ. /Д-Р РЕДДИ/",Протек,Д-р Редди с Лабораторис Лтд / Dr.REDDY's,1.00,18.04,22.00,1.00,9.00,200010000734.00,29,1,5.00

Выводим уникальные значения по столбцу DR_Dat

In [82]:
df.DR_Dat.unique()

<StringArray>
['2022-08-01', '2022-08-02', '2022-08-03', '2022-08-04', '2022-08-05']
Length: 5, dtype: str

Выводим уникальные значения по столбцу DR_Apt

In [84]:
df.DR_Apt.unique()

array([13])

In [209]:
df1 = pd.read_csv('data/data1.csv', encoding='1251')
df1 = df1.groupby('DR_Dat').apply(lambda x: pd.Series({'revenue': sum(x['DR_Kol']*x['DR_CRoz'] - x['DR_SDisc'])})).reset_index()
df1

       DR_Dat  revenue
0  2022-08-01 84681.52
1  2022-08-02 71389.37
2  2022-08-03 78050.82
3  2022-08-04 59187.36
4  2022-08-05 56458.81

In [203]:
df = df.groupby('DR_Dat').apply(lambda x: sum(x['DR_Kol']*x['DR_CRoz'] - x['DR_SDisc'])).reset_index()
df

       DR_Dat        0
0  2022-08-01 84681.52
1  2022-08-02 71389.37
2  2022-08-03 78050.82
3  2022-08-04 59187.36
4  2022-08-05 56458.81

In [207]:
df.columns = ['DR_Dat', 'revenue']

In [210]:
df

       DR_Dat  revenue
0  2022-08-01 84681.52
1  2022-08-02 71389.37
2  2022-08-03 78050.82
3  2022-08-04 59187.36
4  2022-08-05 56458.81

In [261]:
df['revenue_d'] = df['revenue'].rolling(2).apply(lambda x: (x.iloc[1] - x.iloc[0])/x.iloc[0])
df

       DR_Dat  revenue  revenue_d
0  2022-08-01 84681.52        NaN
1  2022-08-02 71389.37      -0.16
2  2022-08-03 78050.82       0.09
3  2022-08-04 59187.36      -0.24
4  2022-08-05 56458.81      -0.05

In [264]:
df['revenue_shifted'] = df['revenue'].shift(1)

In [265]:
df

       DR_Dat  revenue  revenue_d  revenue_shifted
0  2022-08-01 84681.52        NaN              NaN
1  2022-08-02 71389.37      -0.16         84681.52
2  2022-08-03 78050.82       0.09         71389.37
3  2022-08-04 59187.36      -0.24         78050.82
4  2022-08-05 56458.81      -0.05         59187.36

In [266]:
df['revenue_d2'] = (df['revenue'] - df['revenue_shifted']) / df['revenue_shifted']
df

       DR_Dat  revenue  revenue_d  revenue_shifted  revenue_d2
0  2022-08-01 84681.52        NaN              NaN         NaN
1  2022-08-02 71389.37      -0.16         84681.52       -0.16
2  2022-08-03 78050.82       0.09         71389.37        0.09
3  2022-08-04 59187.36      -0.24         78050.82       -0.24
4  2022-08-05 56458.81      -0.05         59187.36       -0.05

In [267]:
df['revenue_d3'] = df['revenue'].pct_change(1)
df

       DR_Dat  revenue  revenue_d  revenue_shifted  revenue_d2  revenue_d3
0  2022-08-01 84681.52        NaN              NaN         NaN         NaN
1  2022-08-02 71389.37      -0.16         84681.52       -0.16       -0.16
2  2022-08-03 78050.82       0.09         71389.37        0.09        0.09
3  2022-08-04 59187.36      -0.24         78050.82       -0.24       -0.24
4  2022-08-05 56458.81      -0.05         59187.36       -0.05       -0.05

**XYZ-анализ**

In [299]:
df = pd.read_csv('data/data1.csv', encoding='1251')

In [269]:
df = df.head()

,DR_Dat,DR_Tim,DR_NChk,DR_NDoc,DR_Apt,DR_Kkm,DR_TDoc,DR_TPay,DR_CDrugs,DR_NDrugs,DR_Suppl,DR_Prod,DR_Kol,DR_CZak,DR_CRoz,DR_SDisc,DR_CDisc,DR_BCDisc,DR_TabEmpl,DR_VZak,DR_Pos
0,2022-08-01,08:06:18,1272,13002561,13,22589,Розничная реализация,18,144734,ГАСТАЛ №12 ТАБ. Д/РАСС.,Пульс,TEVA Pharvaceutical Industries Ltd,1.00,196.71,270.00,0.00,NaN,NaN,29,1,1.00
1,2022-08-01,08:38:53,1273,13002561,13,22589,Розничная реализация,15,69661,"ТОБРОПТ 0,3% 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП. /РОМФАРМ/",Пульс,РОМФАРМ КОМПАНИ ( ROMPHARM ),1.00,106.21,127.00,6.00,9.00,200010004357.00,29,1,1.00
2,2022-08-01,08:55:38,1274,13002561,13,22589,Розничная реализация,18,190635,ЭЛИКВИС 5МГ. №60 ТАБ. П/П/О /ПФАЙЗЕР/БРИСТОЛ-М...,ГРАНД КАПИТАЛ СМОЛЕНСК ООО ФК,Пфайзер,1.00,2320.99,2563.00,76.00,9.00,200010018491.00,29,1,1.00
3,2022-08-01,09:00:40,1275,13002561,13,22589,Розничная реализация,18,276370,АРБИДОЛ МАКСИМУМ 200МГ. №10 КАПС. /ОТИСИФАРМ/Ф...,Пульс,ОТИСИФАРМ ПАО,1.00,445.39,541.00,0.00,NaN,NaN,29,1,1.00
4,2022-08-01,09:04:05,1276,13002561,13,22589,Розничная реализация,15,2303,"ЭНАМ 2,5МГ. №20 ТАБ. /Д-Р РЕДДИ/",Протек,Д-р Редди с Лабораторис Лтд / Dr.REDDY's,1.00,18.04,22.00,1.00,9.00,200010000734.00,29,1,5.00

In [300]:
df = df.groupby(['DR_Dat', 'DR_NDrugs']).agg({'DR_Kol': sum})
df

                                                               DR_Kol
DR_Dat     DR_NDrugs
2022-08-01 911-ВЕНОЛГОН ГЕЛЬ Д/НОГ ПРИ ТЯЖЕСТИ,БОЛИ,ОТЕКАХ...    1.00
           L-ТИРОКСИН 100МКГ. №100 ТАБ. /БЕРЛИН ХЕМИ/            1.00
           L-ТИРОКСИН 50МКГ. №50 ТАБ. /БЕРЛИН ХЕМИ/              1.00
           L-ТИРОКСИН 75МКГ. №100 ТАБ. /БЕРЛИН ХЕМИ/             2.00
           NF ВАТА ХИРУРГ. СТЕР. 100Г. /НЬЮФАРМ/                 1.00
...                                                               ...
2022-08-05 ЭВО ПАНТЕНОЛ ПОМАДА ГИГИЕН. 2,8Г. [EVO] /АВАНТА/      1.00
           ЭМОКСИПИН 10МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ. КРЫШ/КАП.     2.00
           ЭСВИЦИН СР-ВО П/ОБЛЫСЕНИЯ ЛОСЬОН-ТОНИК 250МЛ. Ф...    1.00
           ЭТОРИАКС 90МГ. №7 ТАБ. П/П/О                          1.00
           ЮНИДОКС СОЛЮТАБ 100МГ. №20 ТАБ.ДИСПЕРГ. /АСТЕЛЛАС/    1.00

[1089 rows x 1 columns]

In [289]:
df1 = df.reset_index().groupby('DR_NDrugs').agg({'DR_Dat': 'count'}).reset_index()
xyz_names = list(df1[df1['DR_Dat'] > 1]['DR_NDrugs'])
xyz_names

['L-ТИРОКСИН 50МКГ. №50 ТАБ. /БЕРЛИН ХЕМИ/',
 'L-ТИРОКСИН 75МКГ. №100 ТАБ. /БЕРЛИН ХЕМИ/',
 'АЗАРГА 10МГ/МЛ.+5МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП.',
 'АМОКСИЦИЛЛИН 500МГ. №16 КАПС. /ХЕМОФАРМ/',
 'АРБИДОЛ МАКСИМУМ 200МГ. №10 КАПС. /ОТИСИФАРМ/ФАРМСТАНДАРТ/',
 'АСЕПТИКА САЛФЕТКА СПИРТОВАЯ 60Х100 №20',
 'АСКОРБИНКА ЛУНТИК ВИТ.С КЛУБНИКА №10 ТАБ. (30Г.) /ФАРМ-ПРО/ТИГОДА-ФАРМ/',
 'АСКОРБИНКА ЛУНТИК ВИТ.С №10 ТАБ. (30Г.) /ФАРМ-ПРО/ТИГОДА-ФАРМ/',
 'АСКОРБИНОВАЯ К-ТА 25МГ. ВИШНЯ №10 ТАБ. КРУТКА САХ. /АСКОПРОМ/',
 'АСКОРБИНОВАЯ К-ТА 25МГ. ЯБЛОКО №10 ТАБ. КРУТКА САХ. /АСКОПРОМ/',
 'АСПАРКАМ №60 ТАБ. /ФАРМАПОЛ-ВОЛГА/',
 'АСПЕРА СУПЕРЧИСТОТЕЛ 3МЛ. ФЛ.',
 'АТЕНОЛОЛ РЕНЕВАЛ 50МГ. №30 ТАБ. /ОБНОВЛЕНИЕ/',
 'АТОПИК КРЕМ-СТИК УСПОКАИВАЮЩИЙ Д/ДЕТ. 0+ 4,9МЛ. ПЕНАЛ [ATOPIC]',
 'АТОРВАСТАТИН-СЗ 20МГ. №60 ТАБ. П/П/О /СЕВЕРНАЯ ЗВЕЗДА/',
 'АФОБАЗОЛ 10МГ. №60 ТАБ.',
 'АЦЕТИЛСАЛИЦИЛОВАЯ К-ТА 500МГ. №20 ТАБ. /ФАРМСТАНДАРТ/',
 'АЦИКЛОВИР-БЕЛУПО 5% 10Г. №1 КРЕМ Д/НАРУЖ.ПРИМ. ТУБА /БЕЛУПО/',
 'БЕТАГИСТИН-СЗ 16МГ. №60 ТАБ. /СЕВЕРНАЯ ЗВЕЗДА/',
 'БЕТАЛОК ЗОК 25МГ. №14 ТАБ.ПРОЛОНГ. П/О /АСТРА ЗЕНЕКА/',
 'БИОВИТА ВОДА ПИТЬЕВАЯ СТРУКТУР. 0,6Л. Н/ГАЗ. [BIOVITA]',
 'БИСОПРОЛОЛ 2,5МГ. №30 ТАБ. П/П/О /ВЕРТЕКС/',
 'БИСОПРОЛОЛ 2,5МГ. №60 ТАБ. П/О /ВЕРТЕКС/',
 'БИСОПРОЛОЛ 5МГ. №60 ТАБ. П/П/О /ВЕРТЕКС/',
 'БИФИДУМБАКТЕРИН 5ДОЗ №10 ЛИОФ. Д/СУСП. Д/ПРИЕМА ВНУТРЬ И МЕСТ.ПРИМ. ФЛ. /ЭКОПОЛИС/',
 'БРАЛ 500МГ. №20 ТАБ.',
 'БРИЛЛИАНТОВЫЙ ЗЕЛЕН 1% 25МЛ. №1 СПИРТ. Р-Р Д/НАРУЖ.ПРИМ. ФЛ. /САМАРАМЕДПРОМ/ЖЕНЕЛ/',
 'ВАЗЕЛИН 30Г. МАЗЬ Д/НАРУЖ.ПРИМ. ТУБА /МУРОМСКИЙ/',
 'ВАЛЕРИАНЫ НАСТОЙКА 25МЛ. ФЛ. /ГИППОКРАТ/',
 'ВАЛИДОЛ 60МГ. №10 ТАБ. ПОДЪЯЗЫЧ. /ФАРМСТАНДАРТ/',
 'ВАЛОКОРДИН 20МЛ. КАПЛИ Д/ПРИЕМА ВНУТРЬ ФЛ./КАП.',
 'ВАЛОСЕРДИН 25МЛ. КАПЛИ Д/ПРИЕМА ВНУТРЬ ФЛ. /МОСФАРМА/',
 'ВЕРОШПИРОН 50МГ. №30 КАПС. /ГЕДЕОН РИХТЕР/',
 'ВИТАПРОСТ 10МГ. №10 СУПП. РЕКТ. /НИЖФАРМ/',
 'ВОЛЬТАРЕН 25МГ/МЛ. 3МЛ. №5 Р-Р Д/В/М АМП. /НОВАРТИС/ГЛАКСО/',
 'ГЕКСАЛИЗ №30 ТАБ. Д/РАСС.',
 'ГЕМАТОГЕН РУССКИЙ ДЕТСКИЙ 40Г. ПЛИТКА /ФАРМ-ПРО/',
 'ГИПОСАРТ 16МГ. №28 ТАБ.',
 'ГЛИЦЕРИН 2,11Г. №10 СУПП. РЕКТ. /НИЖФАРМ/',
 'ГЛИЦИН 100МГ. №100 ТАБ. ПОДЪЯЗЫЧ. /БИОТИКИ/',
 'ГЛИЦИН 100МГ. №50 ТАБ. ПОДЪЯЗЫЧ. /БИОТИКИ/',
 'ГЛЮКОЗА 40% 10МЛ. №10 Р-Р Д/ИН. АМП. /ДАЛЬХИМФАРМ/',
 'ДЕЗЛОРАТАДИН-ВЕЛФАРМ 5МГ. №10 ТАБ. П/О',
 'ДЕТРАЛЕКС 1000МГ. №60 ТАБ. П/П/О',
 'ДЕТРИМАКС 2000 240МГ. №60 ТАБ. П/О',
 'ДИАБЕТОН МВ 60МГ. №30 ТАБ. МОДИФ.ВЫСВ. /СЕРВЬЕ/',
 'ДИКЛОФЕНАК 100МГ. №20 ТАБ.ПРОЛОНГ. П/О /НИЖФАРМ/ХЕМОФАРМ/',
 'ДИКЛОФЕНАК 25МГ/МЛ. 3МЛ. №5 Р-Р Д/В/М ВВЕД. АМП. /ХЕМОФАРМ/',
 'ДИКЛОФЕНАК 50МГ. №20 ТАБ.КШ/РАСТВ. П/О /ХЕМОФАРМ/',
 'ДОКСИЦИКЛИН СОЛЮШН ТАБЛЕТС 100МГ. №10 ТАБ.ДИСПЕРГ. /АТОЛЛ/ОЗОН/',
 'ДОКТОР ПЕРЕЦ ЛЕЙКОПЛАСТ. ПЕРЦОВЫЙ 10X18 №1 ПЕРФ. /ВЕРОФАРМ/',
 'ДОЛГИТ 5% 100Г. КРЕМ Д/НАРУЖ.ПРИМ. ТУБА /ДОЛОРГИТ/',
 'ДОНАТ МАГНИЙ ВОДА ГАЗ. 1Л. ПЭТ [DONAT]',
 'ДОНОРМИЛ 15МГ. №30 ТАБ. П/П/О',
 'ДОРИТРИЦИН №10 ТАБ. Д/РАСС.',
 'ИБУКЛИН 400МГ.+325МГ. №10 ТАБ. П/П/О',
 'ИБУПРОФЕН 200МГ. №50 ТАБ. П/О /БОРИСОВСКИЙ/',
 'ИНГАВИРИН 90МГ. №10 КАПС. /ВАЛЕНТА/',
 'ИНДОМЕТАЦИН-СОФАРМА 25МГ. №30 ТАБ.КШ/РАСТВ. П/О',
 'ЙОДА 5% 10МЛ. СПИРТ. Р-Р ФЛ. /ЯРОСЛАВСКАЯ ФФ/',
 'ЙОДА 5% 25МЛ. №1 СПИРТ. Р-Р Д/НАРУЖ.ПРИМ. ФЛ. /ТУЛЬСКАЯ ФФ/',
 'КАЛЕНДУЛЫ НАСТОЙКА 25МЛ. ФЛ. /ГИППОКРАТ/',
 'КАЛИНОВ РОДНИК ВОДА МИНЕР. 0,5Л. Н/ГАЗ.',
 'КАНЕФРОН Н №60 ТАБ. П/О',
 'КЕТОРОЛ ЭКСПРЕСС 10МГ. №20 ТАБ. ДИСПЕРГ. /Д-Р РЕДДИС/',
 'КЛОПИДОГРЕЛ-СЗ 75МГ. №28 ТАБ. П/П/О /СЕВЕРНАЯ ЗВЕЗДА/',
 'КОМБИЛИПЕН 2МЛ. №10 Р-Р Д/В/М АМП.',
 'КОНКОР КОР 2,5МГ. №30 ТАБ. П/П/О /МЕРК/',
 'КОНТЕЙНЕР Д/СБОРА БИОМАТЕРИАЛА 100МЛ. СТЕР. (БАНКА)',
 'КОНТЕЙНЕР Д/СБОРА БИОМАТЕРИАЛА 120МЛ. УНИВЕРС. СТЕР. (БАНКА)',
 'КОРВАЛОЛ 25МЛ. КАПЛИ Д/ПРИЕМА ВНУТРЬ ФЛ. И/У /ФАРМСТАНДАРТ ЛЕКСРЕДСТВА/',
 'КОРНЕРЕГЕЛЬ 5% 10Г. ГЛ. ГЕЛЬ ТУБА',
 'КРЕМ ДЕТСКИЙ РОМАШКА+ВИТ.А+F 75МЛ. /АВАНТА/',
 'Карта LOYALITY 0,01Р',
 'Карта LOYALITY 25Р',
 'ЛАКОМКА ПОМАДА ГИГИЕН. ЯГОДНЫЙ МИКС 2,8Г. /АВАНТА/',
 'ЛЕВОМЕКОЛЬ 40МГ/Г.+7,5МГ/Г. 40Г. №1 МАЗЬ Д/НАРУЖ.ПРИМ. ТУБА /НИЖФАРМ/',
 'ЛЕВОМИЦЕТИН 0,25% 10МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП. /ЛЕККО/',
 'ЛЕВОФЛОКСАЦИН 500МГ. №10 ТАБ. П/П/О /ФАРМСТАНДАРТ-ТОМСКХИМФАРМ/',
 'ЛЕЙКОПЛАСТЫРЬ 1Х500 РУЛОН КОНТ.УПАКОВКА/ПАКЕТ /ВЕРОФАРМ/',
 'ЛЕЙКОПЛАСТЫРЬ 2Х500 ТКАН.ОСНОВА КАТУШКА КАРТОН /ВЕРОФАРМ/',
 'ЛЕЙКОПЛАСТЫРЬ БАКТЕР. 2,5Х7,2 №1 /ВЕРОФАРМ/',
 'ЛЕЙКОПЛАСТЫРЬ БАКТЕР. 4Х10 №1 /ВЕРОФАРМ/',
 'ЛЕЙКОПЛАСТЫРЬ БАКТЕР. 6X10 №1 /ВЕРОФАРМ/',
 'ЛЕКРОЛИН 20МГ/МЛ. 10МЛ. №1 ГЛ.КАПЛИ ФЛ. /САНТЭН/',
 'ЛИЗИНОПРИЛ 10МГ. №60 ТАБ. /ВЕРТЕКС/',
 'ЛОПЕРАМИД-АКРИХИН 2МГ. №20 КАПС. /АКРИХИН/',
 'ЛЮКСПЛАСТ ЛЕЙКОПЛАСТ. БАКТЕР. 19Х72ММ ПЕРФ. ТЕЛЕСН. ПОЛИМЕР. №10 [LUXPLAST]',
 'МАГНЕЛИС В6 №120 ТАБ. П/О',
 'МАСКА МЕД. ТРЕХСЛОЙНАЯ (3-Х) НА РЕЗИНКЕ №5',
 'МЕЗИМ-ФОРТЕ №20 ТАБ. П/О /БЕРЛИН-ХЕМИ/',
 'МЕЗИМ-ФОРТЕ №80 ТАБ. П/О /БЕРЛИН-ХЕМИ/',
 'МЕКСИДОЛ 125МГ. №50 ТАБ. П/П/О /ФАРМАСОФТ/ЗИО ЗДОРОВЬЕ/',
 'МЕНОВАЗИН 40МЛ. №1 СПИРТ. Р-Р Д/НАРУЖ.ПРИМ. ФЛ. /САМАРАМЕДПРОМ/',
 'МЕНОВАЗИН 40МЛ. №1 СПИРТ. Р-Р Д/НАРУЖ.ПРИМ. ФЛ. /ТУЛЬСКАЯ ФФ/',
 'МЕТИЛУРАЦИЛ 10% 25Г. МАЗЬ Д/МЕСТ. И НАРУЖ.ПРИМ. ТУБА /НИЖФАРМ/',
 'МЕТРОГИЛ ДЕНТА 20Г. №1 ГЕЛЬ СТОМАТ. ТУБА',
 'МЕТРОНИДАЗОЛ 250МГ. №20 ТАБ. /МЕДИСОРБ/',
 'МИГ 400МГ. №20 ТАБ. П/П/О /БЕРЛИН-ХЕМИ/',
 'МИДОКАЛМ 150МГ. №30 ТАБ. П/П/О /ГЕДЕОН РИХТЕР/',
 'МИКРОЛАКС 5МЛ. №4 Р-Р Д/РЕКТ. ВВЕД. МИКРОКЛИЗМА',
 'МИЛДРОНАТ 100МГ/МЛ. 5МЛ. №10 Р-Р Д/В/В,В/М И ПАРАБУЛЬБ. ВВЕД. АМП. /ГРИНДЕКС/',
 'МОКСОНИДИН-СЗ 0,2МГ. №60 ТАБ. П/П/О /СЕВЕРНАЯ ЗВЕЗДА/',
 'НАЙЗ 100МГ. №30 ТАБ.',
 'НАНОПЛАСТ ФОРТЕ ПЛАСТЫРЬ ОБЕЗБОЛ. 9Х12СМ. №3',
 'НАТРИЯ ХЛОРИД 0,9% 100МЛ. №28 Р-Р Д/ИНФ. /ЭСКОМ/',
 'НАФТИЗИН 0,1% 15МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. /СЛАВЯНСКАЯ АПТЕКА/',
 'НИМЕСИЛ 100МГ. 2Г. №30 ГРАН. Д/СУСП. Д/ПРИЕМА ВНУТРЬ ПАК. /ГУИДОТТИ/МЕНАРИНИ/',
 'НИФЕДИПИН 10МГ. №50 ТАБ. П/П/О /ОЗОН/',
 'НО-ШПА 40МГ. №24 ТАБ. /ХИНОИН/',
 'НОЛИПРЕЛ А ФОРТЕ 5МГ.+1,25МГ. №30 ТАБ. П/П/О',
 'НОЛЬПАЗА 20МГ. №14 ТАБ.КШ/РАСТВ. П/О /KRKA/',
 'НОЛЬПАЗА 20МГ. №28 ТАБ.КШ/РАСТВ. П/О /KRKA/',
 'НУРОФЕН 100МГ/5МЛ. 100МЛ. СУСП. КЛУБНИКА Д/ДЕТЕЙ ФЛ. /РЕКИТТ БЕНКИЗЕР/',
 'НУРОФЕН ЭКСПРЕСС ФОРТЕ 400МГ. №20 КАПС. /РЕКИТТ БЕНКИЗЕР/',
 'ОМЕЗ 20МГ. №30 КАПС. /Д-Р РЕДДИ/',
 'ОМЕПРАЗОЛ 20МГ. №30 КАПС. /ПРОИЗВОДСТВО МЕДИКАМЕНТОВ/',
 'ОФТАН-КАТАХРОМ 10МЛ. ГЛ.КАПЛИ ФЛ.',
 'ПАКЕТ',
 'ПАНАНГИН 158МГ+140МГ. №50 ТАБ. П/П/О /ГЕДЕОН РИХТЕР/',
 'ПАНКРЕАТИН 25ЕД №60 ТАБ.КШ/РАСТВ. П/О БАНКА /БИОСИНТЕЗ/',
 'ПАНКРЕАТИН 30ЕД №60 ТАБ.КШ/РАСТВ. П/О БАНКА /ФАРМПРОЕКТ/',
 'ПАРАЦЕТАМОЛ 500МГ. №20 ТАБ. /ФАРМСТАНДАРТ/',
 'ПАСКАЛЬ ШПРИЦ 3-Х КОМП. 3МЛ. С ИГЛОЙ 22G 0,7Х40ММ. №10 [PASCAL]',
 'ПАСКАЛЬ ШПРИЦ 3-Х КОМП. 5МЛ. С ИГЛОЙ 22G 0,7Х30ММ. №10 [PASCAL]',
 'ПЕНТАЛГИН №24 ТАБ. П/П/О /ОТИСИФАРМ/',
 'ПЕРЕКИСЬ ВОДОРОДА 3% 100МЛ. №1 Р-Р ДЕЗ.СР-ВО ФЛ. (НДС 20%)',
 'ПЕРИНЕВА 4МГ. №30 ТАБ. /KRKA/',
 'ПИКАМИЛОН 20МГ. №30 ТАБ. /ФАРМСТАНДАРТ/',
 'ПОЛИДЕКСА С ФЕНИЛЭФРИНОМ 15МЛ. НАЗАЛ.СПРЕЙ ФЛ.',
 'ПУЛЬМИКОРТ 0,25МГ/МЛ. 2МЛ. №20 СУСП. Д/ИНГ. КОНТ. /АСТРА ЗЕНЕКА/',
 'ПУСТЫРНИКА НАСТОЙКА 25МЛ. ФЛ. /ГИППОКРАТ/',
 'ПУСТЫРНИКА ЭКСТРАКТ 14МГ. №50 ТАБ. /ФАРМСТАНДАРТ/',
 'РИГЕВИДОН 0,15МГ+0,03МГ. №63 (21Х3) ТАБ. П/О /ГЕДЕОН РИХТЕР/',
 'РИНОНОРМ-ТЕВА 0,1% 140МКГ/ДОЗА 20МЛ. НАЗАЛ.СПРЕЙ ФЛ. /ТЕВА/',
 'РИНОРУС 0,1% 10МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. И/У /СИНТЕЗ/',
 'РИНОСТОП 0,1% 10МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. /ОТИСИФАРМ/ЛЕККО/ФАРМСТАНДАРТ ЛЕКСРЕДСТВА/',
 'РИНОСТОП 0,1% 15МЛ. НАЗАЛ.СПРЕЙ ФЛ. /ОТИСИФАРМ/ЛЕККО/ФАРМСТАНДАРТ ЛЕКСРЕДСТВА/',
 'РОМАШКИ ЦВЕТКИ 1,5Г. №20 ПАК. /КРАСНОГОРСК/',
 'САЛИПОД ЛЕЙКОПЛАСТ. МОЗОЛЬНЫЙ 6Х10СМ. /ВЕРОФАРМ/',
 'САЛИЦИЛОВАЯ К-ТА 2% 40МЛ. №1 СПИРТ. Р-Р Д/НАРУЖ.ПРИМ. ФЛ. /ИВАНОВСКАЯ ФФ/',
 'СВЯТОЙ ИСТОЧНИК ВОДА ПИТЬЕВАЯ 0,5Л. Н/ГАЗ. ПЭТ',
 'СИГНИЦЕФ 0,5% 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП. /СЕНТИСС/ПРОМЕД/',
 'СИЛЬВЕР КАПИТАН БАТОНЧИК КОКОС БЕЛ.ГЛАЗ. 50Г.',
 'СИНАФЛАН 0,025% 15Г. МАЗЬ Д/НАРУЖ.ПРИМ. ТУБА /МУРОМСКИЙ ЗАВОД/',
 'СНУП 0,1% 90МКГ/ДОЗА 15МЛ. НАЗАЛ.СПРЕЙ ФЛ. /ШТАДА/',
 'СОРБИФЕР ДУРУЛЕС 320МГ/60МГ. №50 ТАБ. П/О',
 'СОТАГЕКСАЛ 80МГ. №20 ТАБ. /ГЕКСАЛ АГ/',
 'СПЛАТ ЗУБ.ПАСТА ЛЕЧЕБНЫЕ ТРАВЫ 100МЛ. [SPLAT]',
 'СТАРЫЙ ИСТОЧНИК СЛАВЯНОВСКАЯ ВОДА МИНЕР. ЭЛИТНАЯ 1Л.',
 'СТЕЛЛАНИН 3% 20Г. МАЗЬ Д/НАРУЖ.ПРИМ. ТУБА',
 'СТОПСЕПТ ПЛЮС 90% 100МЛ. ДЕЗ.СР-ВО ФЛ.',
 'СТРЕПТОЦИД 10Г. №1 ПОР. Д/НАРУЖ.ПРИМ. БАНКА ДОЗ. /ЛЕКАРЬ/',
 'СФМ СИСТЕМА Д/ПЕРЕЛИВ. ИНФУЗ. Р-РОВ №1 ПЛАСТ.ИГЛА [SFM]',
 'СФМ ШПРИЦ 2МЛ. 3-Х КОМП. 0,63Х32ММ 23G №100 [SFM]',
 'СФМ ШПРИЦ 5МЛ. 3-Х КОМП. 0,7Х40ММ 22G №100 [SFM]',
 'ТАУРИН 4% 10МЛ. ГЛ.КАПЛИ ФЛ./КАП. /СЛАВЯНСКАЯ АПТЕКА/',
 'ТАУФОН 4% 10МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП. /ОТИСИФАРМ/ФАРМСТАНДАРТ/',
 'ТЕРАФЛЮ ЭКСТРА ЛИМОН ОТ ГРИППА И ПРОСТУДЫ 15Г. №10 ПОР. Д/Р-РА Д/ПРИЕМА ВНУТРЬ ПАК.',
 'ТЕТРАЦИКЛИНОВАЯ 1% 5Г. ГЛ. МАЗЬ ТУБА /ТАТХИМФАРМ/',
 'ТОЛПЕРИЗОН 150МГ. №30 ТАБ. П/П/О /МЕДИСОРБ/',
 'ТРИМЕТАЗИДИН-АКОС МВ 35МГ. №60 ТАБ. МОДИФ.ВЫСВ. /БИОКОМ/',
 'ТРОКСЕРУТИН ВРАМЕД 2% 40Г. ГЕЛЬ Д/НАРУЖ.ПРИМ. ТУБА /СОФАРМА/',
 'УГОЛЬ АКТИВИРОВАННЫЙ 250МГ. №50 ТАБ. /ФАРМСТАНДАРТ ЛЕКСРЕДСТВА/',
 'ФЕРРОГЕМАТОГЕН 50Г. ПАСТИЛКА ЖЕВ. (ПЛИТКА)',
 'ФЛУИМУЦИЛ 600МГ. №10 ШИП.ТАБ. /ЗАМБОН/',
 'ФОСФОГЛИВ ФОРТЕ 65МГ+300МГ. №50 КАПС. /ФАРМСТАНДАРТ/',
 'ФУКОРЦИН 25МЛ. Р-Р Д/НАРУЖ.ПРИМ. ФЛ. /ТУЛЬСКАЯ ФФ/',
 'ФУРАЦИЛИН АВЕКСИМА 20МГ. №10 ШИП.ТАБ. Д/Р-РА Д/МЕСТ. И НАРУЖ.ПРИМ.',
 'ХЕЛП БИНТ СТЕР. 7МХ14СМ И/У [HELP]',
 'ЦИАНОКОБАЛАМИН 0,5МГ/МЛ. 1МЛ. №10 Р-Р Д/ИН. АМП. (ВИТАМИН В12) /ДАЛЬХИМФАРМ/',
 'ЦИПРОЛЕТ А 500МГ.+600МГ. №10 ТАБ. П/О',
 'ЦИСТОН №100 ТАБ.',
 'ЦИТРАМОН П №10 ТАБ. /ФАРМСТАНДАРТ/',
 'ЦИТРАМОН П №20 ТАБ. /МЕДИСОРБ/',
 'ЦИТРАМОН П №20 ТАБ. /ФАРМСТАНДАРТ/',
 'ЭВЕРС-ЛАЙФ САЛФЕТКА СТЕР. 2-Х СЛ. 16Х14СМ. №10 [EVERS LIFE]',
 'ЭВО ПАНТЕНОЛ ПОМАДА ГИГИЕН. 2,8Г. [EVO] /АВАНТА/',
 'ЭЛИКВИС 5МГ. №60 ТАБ. П/П/О /ПФАЙЗЕР/БРИСТОЛ-МАЙЕРС/',
 'ЭМОКСИПИН 10МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ. КРЫШ/КАП.',
 'ЭНАЛАПРИЛ 5МГ. №20 ТАБ. /ХЕМОФАРМ/',
 'ЭСВИЦИН СР-ВО П/ОБЛЫСЕНИЯ ЛОСЬОН-ТОНИК 250МЛ. ФЛ. /ВИО-ФАРМ/']

In [302]:
df = df.reset_index()
df = df[df['DR_NDrugs'].isin(xyz_names)]
df = df.groupby('DR_NDrugs').apply(lambda x: x.std()/x.mean())
df

C:\Users\User\AppData\Local\Temp\ipykernel_9316\4270249517.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df = df.groupby('DR_NDrugs').apply(lambda x: x.std()/x.mean())

                                                    DR_Kol
DR_NDrugs
L-ТИРОКСИН 50МКГ. №50 ТАБ. /БЕРЛИН ХЕМИ/               NaN
L-ТИРОКСИН 75МКГ. №100 ТАБ. /БЕРЛИН ХЕМИ/              NaN
АЗАРГА 10МГ/МЛ.+5МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП.      NaN
АМОКСИЦИЛЛИН 500МГ. №16 КАПС. /ХЕМОФАРМ/               NaN
АРБИДОЛ МАКСИМУМ 200МГ. №10 КАПС. /ОТИСИФАРМ/ФА...     NaN
...                                                    ...
ЭВО ПАНТЕНОЛ ПОМАДА ГИГИЕН. 2,8Г. [EVO] /АВАНТА/       NaN
ЭЛИКВИС 5МГ. №60 ТАБ. П/П/О /ПФАЙЗЕР/БРИСТОЛ-МА...     NaN
ЭМОКСИПИН 10МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ. КРЫШ/КАП.      NaN
ЭНАЛАПРИЛ 5МГ. №20 ТАБ. /ХЕМОФАРМ/                     NaN
ЭСВИЦИН СР-ВО П/ОБЛЫСЕНИЯ ЛОСЬОН-ТОНИК 250МЛ. Ф...     NaN

[182 rows x 1 columns]

In [298]:
df

                                                    level_0  index  DR_Kol XYZ
DR_NDrugs
L-ТИРОКСИН 50МКГ. №50 ТАБ. /БЕРЛИН ХЕМИ/               1.41   1.41    0.00   X
L-ТИРОКСИН 75МКГ. №100 ТАБ. /БЕРЛИН ХЕМИ/              1.40   1.40    0.47   Z
АЗАРГА 10МГ/МЛ.+5МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП.      1.36   1.36    0.00   X
АМОКСИЦИЛЛИН 500МГ. №16 КАПС. /ХЕМОФАРМ/               0.60   0.60    0.47   Z
АРБИДОЛ МАКСИМУМ 200МГ. №10 КАПС. /ОТИСИФАРМ/ФА...     1.13   1.13    0.43   Z
...                                                     ...    ...     ...  ..
ЭВО ПАНТЕНОЛ ПОМАДА ГИГИЕН. 2,8Г. [EVO] /АВАНТА/       0.15   0.15    0.47   Z
ЭЛИКВИС 5МГ. №60 ТАБ. П/П/О /ПФАЙЗЕР/БРИСТОЛ-МА...     0.42   0.42    0.00   X
ЭМОКСИПИН 10МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ. КРЫШ/КАП.      0.31   0.31    0.47   Z
ЭНАЛАПРИЛ 5МГ. №20 ТАБ. /ХЕМОФАРМ/                     0.41   0.41    0.47   Z
ЭСВИЦИН СР-ВО П/ОБЛЫСЕНИЯ ЛОСЬОН-ТОНИК 250МЛ. Ф...     0.55   0.55    0.29   Z

[182 rows x 4 columns]

In [296]:
df['XYZ'] = np.where(df['DR_Kol'] < 0.1, 'X', np.where(df['DR_Kol'] < 0.25, 'Y', 'Z'))

In [297]:
df

                                                    level_0  index  DR_Kol XYZ
DR_NDrugs
L-ТИРОКСИН 50МКГ. №50 ТАБ. /БЕРЛИН ХЕМИ/               1.41   1.41    0.00   X
L-ТИРОКСИН 75МКГ. №100 ТАБ. /БЕРЛИН ХЕМИ/              1.40   1.40    0.47   Z
АЗАРГА 10МГ/МЛ.+5МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП.      1.36   1.36    0.00   X
АМОКСИЦИЛЛИН 500МГ. №16 КАПС. /ХЕМОФАРМ/               0.60   0.60    0.47   Z
АРБИДОЛ МАКСИМУМ 200МГ. №10 КАПС. /ОТИСИФАРМ/ФА...     1.13   1.13    0.43   Z
...                                                     ...    ...     ...  ..
ЭВО ПАНТЕНОЛ ПОМАДА ГИГИЕН. 2,8Г. [EVO] /АВАНТА/       0.15   0.15    0.47   Z
ЭЛИКВИС 5МГ. №60 ТАБ. П/П/О /ПФАЙЗЕР/БРИСТОЛ-МА...     0.42   0.42    0.00   X
ЭМОКСИПИН 10МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ. КРЫШ/КАП.      0.31   0.31    0.47   Z
ЭНАЛАПРИЛ 5МГ. №20 ТАБ. /ХЕМОФАРМ/                     0.41   0.41    0.47   Z
ЭСВИЦИН СР-ВО П/ОБЛЫСЕНИЯ ЛОСЬОН-ТОНИК 250МЛ. Ф...     0.55   0.55    0.29   Z

[182 rows x 4 columns]

In [293]:
a = {'b': [1]}
a = pd.DataFrame(a)
a

   b
0  1

In [276]:
a['b'].std()

0.7071067811865476

In [279]:
np.std(a['b'])

0.0